version: "3"

services:
  db:
    image: "postgres:15.1"

    restart: always

    ports:
      - 7000:5432
    
    env_file:
      - ".env"
    environment:
      PGDATA: /var/lib/postgresql/data/orders/

    volumes:
      - pg-data:/var/lib/postgresql/data/orders

    networks:
      - orders

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  redis_service:

    image: "redis:7.2.2-alpine"

    restart: always

    ports: 
    - 6001:6379

      #command:
      #- /bin/sh
      #- -c
    # - Double dollars, so that the variable is not expanded by Docker Compose
    # - Surround by quotes, so that the shell does not split the password
    # - The ${variable:?message} syntax causes shell to exit with a non-zero
    #   code and print a message, when the variable is not set or empty
    #- redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - pg-data:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    env_file:
      - ".env"
    networks:
      - orders

networks:
  orders:
    driver: bridge

volumes:
  pg-data:
